version: '3'

services:
  backend:
      build: .
      container_name: docker_fastapi
      # command: bash -c "python3 main.py"
      volumes:
          - .:/app
      ports:
          - "8080:8080"